# Generated by Django 4.1 on 2022-10-07 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0002_alter_email_email'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Email',
            new_name='UserInfo',
        ),
    ]
