# Generated by Django 4.1 on 2022-11-07 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsletter',
            name='published',
            field=models.BooleanField(default=False),
        ),
    ]
