# Generated by Django 4.1 on 2022-10-14 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_alter_post_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='source',
            field=models.URLField(blank=True, unique=True),
        ),
    ]
