# Generated by Django 4.1 on 2022-11-09 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscribers', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscriber',
            name='otp_num',
        ),
    ]
