# Generated by Django 4.1 on 2022-10-08 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscribers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='unsubscriber',
            name='first_name',
            field=models.CharField(default='temp', max_length=25),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='unsubscriber',
            name='last_name',
            field=models.CharField(blank=True, max_length=25),
        ),
    ]
