# Generated by Django 4.1 on 2022-10-16 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscribers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriber',
            name='delivered_emails',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='subscriber',
            name='opened_emails',
            field=models.IntegerField(default=0),
        ),
    ]
